apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-app
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - name: nginx-container
        image: backtojuan/simplewebapplication:latest 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-app-service
spec:
  selector:
    app: nginx-web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

